# Generated by Django 2.2.6 on 2019-11-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191120_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='portfolio_image',
            field=models.ImageField(blank=True, upload_to='user-profile-images/'),
        ),
    ]
