# Generated by Django 2.2.6 on 2019-12-01 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191130_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='portfolio_image',
            new_name='user_profile_image',
        ),
    ]
