# Generated by Django 2.2.6 on 2019-11-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20191114_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='support_image',
            field=models.ImageField(blank=True, upload_to='contact-support-images/'),
        ),
    ]
