# Generated by Django 2.2.6 on 2019-11-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_contact_support_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='employer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='ContactWork',
        ),
    ]
