# Generated by Django 2.2.6 on 2019-12-24 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_contact_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlog',
            name='support_image',
            field=models.ImageField(blank=True, upload_to='network-log-support-images/'),
        ),
    ]
