# Generated by Django 2.2.6 on 2019-12-31 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_contactlog_support_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'permissions': [('pro', 'Can create unlimited contacts')]},
        ),
    ]
