# Generated by Django 2.2.6 on 2019-12-31 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20191230_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'permissions': [('network-pro', 'Can create unlimited contacts')]},
        ),
    ]
