# Generated by Django 2.2.6 on 2020-01-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_auto_20200101_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='when_to_contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
