# Generated by Django 2.2.6 on 2020-01-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_auto_20200101_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='when_to_contact',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
