# Generated by Django 2.2.6 on 2020-01-02 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_contact_when_to_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='when_to_contact',
        ),
    ]
