# Generated by Django 2.2.6 on 2019-12-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_listentry_support_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
