# Generated by Django 2.2.6 on 2019-12-13 15:53

from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_list_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listentry',
            name='support_image',
            field=image_optimizer.fields.OptimizedImageField(blank=True, upload_to='list-support-images/'),
        ),
    ]
