# Generated by Django 2.2.6 on 2019-12-13 17:09

from django.db import migrations, models
import emoji_picker.widgets


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20191213_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listentry',
            name='body',
            field=models.TextField(verbose_name=emoji_picker.widgets.EmojiPickerTextareaAdmin),
        ),
        migrations.AlterField(
            model_name='listentry',
            name='support_image',
            field=models.ImageField(blank=True, upload_to='list-support-images/'),
        ),
    ]
