# Generated by Django 2.2.6 on 2019-12-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_auto_20191213_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listentry',
            name='body',
            field=models.TextField(),
        ),
    ]
