# Generated by Django 2.2.6 on 2019-12-27 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_auto_20191213_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'permissions': [('pro', 'Can create unlimited lists (gardens)')]},
        ),
    ]
