# Generated by Django 2.2.6 on 2019-12-31 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_list_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'permissions': [('garden_permission', 'Can create unlimited lists (gardens)')]},
        ),
    ]
