# Generated by Django 2.2.6 on 2019-12-31 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_auto_20191230_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'permissions': [('garden-pro', 'Can create unlimited lists (gardens)')]},
        ),
    ]
