# Generated by Django 2.2.4 on 2019-09-10 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_journals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='to_journal_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('parent_journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='to_journals.to_journal')),
            ],
        ),
    ]
