# Generated by Django 2.2.6 on 2019-10-13 17:39

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_journals', '0003_to_journal_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_journal',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name'),
        ),
    ]
