# Generated by Django 2.2.6 on 2019-10-15 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('to_journals', '0004_auto_20191013_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_journal_entry',
            name='journal_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
