# Generated by Django 2.2.6 on 2019-10-15 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_journals', '0005_to_journal_entry_journal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_journal_entry',
            name='parent_journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_journals.to_journal'),
        ),
    ]
