# Generated by Django 2.2.6 on 2019-10-15 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_journals', '0006_auto_20191015_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_journal_entry',
            name='parent_journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='to_journals.to_journal'),
        ),
    ]
