# Generated by Django 2.2.6 on 2019-10-17 03:26

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_journals', '0007_auto_20191015_0302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='to_journal',
            old_name='name',
            new_name='journal_name',
        ),
        migrations.RenameField(
            model_name='to_journal_entry',
            old_name='parent_journal',
            new_name='journal_name',
        ),
        migrations.AlterField(
            model_name='to_journal',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='journal_name'),
        ),
    ]
