# Generated by Django 2.2.6 on 2019-10-17 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_journals', '0008_auto_20191017_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_journal_entry',
            name='journal_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_journals.to_journal'),
        ),
    ]
