# Generated by Django 2.2.6 on 2019-10-27 03:56

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_journals', '0009_auto_20191017_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_journal',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='journal_name'),
        ),
    ]
