# Generated by Django 2.2.6 on 2019-10-29 14:37

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('to_journals', '0010_auto_20191026_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_journal_entry',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
