# Generated by Django 2.2.6 on 2019-11-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_journals', '0012_auto_20191029_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_journal_entry',
            name='support_image',
            field=models.ImageField(blank=True, upload_to='entry-support-images/'),
        ),
    ]
