# Generated by Django 2.2.6 on 2019-12-31 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_journals', '0014_to_journal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_journal',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='journal-desc-image/'),
        ),
    ]
