# Generated by Django 2.2.6 on 2019-12-31 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_journals', '0015_to_journal_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='to_journal',
            options={'permissions': [('pro', 'Can create unlimited journals')]},
        ),
    ]
