# Generated by Django 2.2.6 on 2019-12-31 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_journals', '0016_auto_20191230_2324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='to_journal',
            options={'permissions': [('journal_permission', 'Can create unlimited journals')]},
        ),
    ]
