# Generated by Django 2.2.6 on 2019-12-31 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_journals', '0017_auto_20191230_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='to_journal',
            options={'permissions': [('journal-pro', 'Can create unlimited journals')]},
        ),
    ]
